### ISSUE TITLE
Cannot read property 'length' of undefined]

### ISSUE THREAD

**Issue by edencorbin** [node-modules/node-biginteger#13]
Maybe I am using this node script wrong, I get a Cannot read property 'length' of undefined, with the following

var n = BigInteger.fromString('1717725000000857021', 16);
    var n2 = n.add(1);
    var n3 = n2.toString(16);
    console.log(n3);

Any help?
PS: my goal is to add 1 to a very big number.

**Comment by Yaffle** [comment]
@edencorbin , did you try to `n.add(BigInteger.fromString('1', 10));` ?

**Comment by edencorbin** [comment]
Nope, I ended up using a different library, and furthermore, what I thought needed to be augmented by 1 didn't, lol, this is very likely the solution though this can be closed, thank you.
