### ISSUE TITLE
Missing implementation of MutableBigInteger modInverseBP2() function

### ISSUE THREAD

**Issue by ffbenedetti** [node-modules/node-biginteger#8]
The modInverse() function fails for some BigInteger objects invoking the MutableBigInteger modInverseBP2() function that is not implemented.
See lib/MutableBigInteger.js  line  1099: var y1 = this.modInverseBP2(oddMod, powersOf2);

**Comment by coolme200** [comment]
Can you provide examples of data calculation?

**Comment by ffbenedetti** [comment]
This is failing:
e.modInvert(mod)
with:
e = 65537
mod = 136819944083170987410115337460869659086272414376932326865658182937447677292599784392202871080942827791338180224888581576438094692682079190465150572950871353178047481763288869099575813102669259887353768993251201467531566358345847054903381797710297310764761980315254200663853027169395316015133030015232408642296

**Comment by coolme200** [comment]
node-biginteger@0.0.9
